Setup Travis CI
atlassian/ssh-ubuntu pull request #2
Opened 2019-02-05 19:06 UTC by wyrzyk

2019-02-06 10:22 UTC, sebapawlak commented
Do we need gradle plugin 0.5.0 here as well?

2019-02-06 10:52 UTC, dagguh requested changes

2019-02-06 10:52 UTC, dagguh commented on .travis.yml
> +      script: ./scripts/travis-release.sh
Gotta add the `./scripts/travis-release.sh` file

2019-02-06 10:52 UTC, dagguh commented on .travis.yml
> +    - $HOME/.gradle/wrapper/
Let's add the trailing blank line, just to get rid of the red here ;)

2019-02-06 10:52 UTC, dagguh commented on .travis.yml
> +    - stage: release
Since we're enabling releases here, we should use `gradle-release:0.5.0` to get the proper POM SCM

2019-02-07 11:57 UTC, sebapawlak submitted a review, later dismissed

2019-02-13 06:30 UTC, merged